### ISSUE TITLE
The site css does not differentiate between h4 to h8

### ISSUE THREAD

**Issue by paradite** [nus-oss/cs3281#28]
I am trying to break down the contribution to different sub-projects using h4 and h6, it works on github-flavoured markdown but not on the site:
http://nus-oss.github.io/cs3281/teams/socketio/

HTML:

```
<h4 id="contribution-to-project-si">Contribution to project SI</h4>
<h6 id="main-codebase">Main codebase</h6>
```

illustration using github markdown support for comments:
###### h6

relevant css code on the website:

```
  .post-content h4, .post-content h5, .post-content h6, .post-content h7, .post-content h8 {
    font-size: 20px;
    font-family: 'Source Sans Pro', sans-serif;
    padding: 0px 10px;
    margin-bottom: 20px; }
```

**Comment by lowjoel** [comment]
I thought I fixed it? Otherwise, PR welcome :)

**Comment by paradite** [comment]
okay PR in a few mintues

**Comment by lowjoel** [comment]
@paradite I think from h6 to h8 it's so small... there really won't be much difference.

**Comment by paradite** [comment]
i am fixing h5 and h6

**Comment by lowjoel** [comment]
okay, that's fine.
