### ISSUE TITLE
Missing background image

### ISSUE THREAD

**Issue by thngkaiyuan** [nus-oss/cs3281#57]
The background image used in `main.css` (`http://lakto.org/assets/img/cover.jpg`) is missing.

This is what the module page looks like now (it's normal if you can't see anything):
![image](https://cloud.githubusercontent.com/assets/10496851/13722147/94b52780-e875-11e5-9cb2-ec17b936b6b7.png)

**Comment by lowjoel** [comment]
Want to replace it with something else? :stuck_out_tongue:

**Comment by thngkaiyuan** [comment]
My artistic taste is not very good :disappointed:

**Comment by lowjoel** [comment]
https://commons.wikimedia.org/wiki/Commons:Picture_of_the_day pick one? :smile:

**Comment by thngkaiyuan** [comment]
How does this look? 

![image](https://cloud.githubusercontent.com/assets/10496851/13722218/b5814496-e878-11e5-8051-c5196a388b11.png)

Using `http://images.freepicturesweb.com/img1/07/17/33.jpg` as the background image.

**Comment by lowjoel** [comment]
blue-tinted Vista wallwaper? :stuck_out_tongue: 

please submit a PR!
